# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#   configuration: docs/conf.py

# Build documentation with MkDocs
mkdocs:
  configuration: bindings/python/cinterop/mkdocs.yml

# Optionally build your docs in additional formats such as PDF
# formats:
#   - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: bindings/python/cinterop/docs/requirements.txt
    # method: setuptools # fails with "error: package directory 'cinterop' does not exist"
    - method: pip
      path: ./bindings/python/cinterop

## Tried to use conda; worked for a bit but then failed to work with typehints added
# on the readthedoc build. but works locally. Revert to pip requirements instead
# since anyway it looks like pip install mkdocs is done on top of conda setup.
# conda:
#   environment: docs/environment.yml