[mypy]
ignore_missing_imports = true
exclude = tests/fixtures/
warn_unused_ignores = true
show_error_codes = true

; Not sure the following works as expected. 
[mypy-six]
ignore_missing_imports = true

[mypy-pytz]
ignore_missing_imports = true